	ORG	0000H
	JMP	MAIN
	ORG	0050H
MAIN:
	MOV	TMOD,#00100000B		;NO GATE/T0/MODE2
	MOV	TL1,#0E6H
	MOV	TH1,#0E6H
	SETB TR1				;T1 RUN+NO GATE = ALWAYS RUN
	CLR	 SM0
	SETB SM1				;MODE1
	CLR	 SM2
	SETB REN	  			;RECEIVE ENABLE
LOOP:  
	CLR	RI					;RI=0
	JNB	RI,$
	MOV	A,SBUF				;接收資料
	ADD	A,#20H				;變小寫
	CLR TI					;重設傳輸
	MOV	SBUF,A 				;傳輸
	JNB TI,$				;等待傳輸完成
	JMP LOOP
END